on:
  push:
    branches: [ master ]
  workflow_dispatch:

name: tests

jobs:
  tests:
    name: PHP-${{ matrix.php }}-${{ matrix.os }}

    env:
      extensions: json, pdo, xml
      TARGET_DIR: ${{ github.workspace }}/wr-php${{ matrix.php }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

        php:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"

    steps:
      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2

        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          coverage: none
          tools: composer:v2

      - name: Check PHP
        run: php -v

      - name: Create new directory for PHP version
        run: mkdir -p "${{ env.TARGET_DIR }}"

      - name: Install webrotor
        run: cd ${{ env.TARGET_DIR }} && composer require phphleb/webrotor --with-dependencies

      - name: Install tests
        run:  cd ${{ env.TARGET_DIR }} && composer require phphleb/webrotor-tests --with-dependencies

      - name: Composer autoload
        run:  cd ${{ env.TARGET_DIR }} && composer dump-autoload

      - name: Run start tests
        run: php ${{ env.TARGET_DIR }}/vendor/bin/phpunit --configuration=${{ env.TARGET_DIR }}/vendor/phphleb/webrotor-tests/phpunit.xml --testsuite start

      - name: Run unit tests
        run: php ${{ env.TARGET_DIR }}/vendor/bin/phpunit --configuration=${{ env.TARGET_DIR }}/vendor/phphleb/webrotor-tests/phpunit.xml --testsuite unit

      - name: Run feature tests
        run: php ${{ env.TARGET_DIR }}/vendor/bin/phpunit --configuration=${{ env.TARGET_DIR }}/vendor/phphleb/webrotor-tests/phpunit.xml --testsuite feature
